### ISSUE TITLE
Mouse Lag

### ISSUE THREAD

**Issue by WasabiCannon** [klayveR/xenontrade#13]
Win 10 Pro 64bit
When loading xenontrade and being on the desktop the mouse will become basically unusable due to the lag. Opening up task manager seems to work around this until you get into the game at which so far the issue does not happen.

**Comment by klayveR** [comment]
Is this still an issue?

**Comment by klayveR** [comment]
Could not reproduce, please provide more information and reopen if this is still and issue.

**Comment by WasabiCannon** [comment]
What type of information do you need to drill down into this?
I tried to reinstall it and now I cant even manage to get the lag to stop until I manage to close out of XenonTrade.

Not sure if it will help but here is a DXDiag.
[DxDiag.txt](https://github.com/klayveR/xenontrade/files/2413613/DxDiag.txt)

**Comment by klayveR** [comment]
The following may or may not explain why this is happening. Unfortunately I have never heard of an error like this and I'm not using Windows, so I'm afraid I can't help you a lot. It could be completely unrelated to your issue.

```
+++ WER0 +++:
Fault bucket 1728115910268795609, type 5
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: XenonTrade.exe
P2: 0.3.4.0
P3: 5b7daf5c
P4: 4cae
P5: 67246080
P6: 
P7: 
P8: 
P9: 
P10: 
```

Since it's in the dxdiag, it might be a problem with your video card (which is what google is suggesting too). Make sure everything is up to date and scan for malware.
